version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: YourStrong!Passw0rd
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./sqlserverdata:/var/opt/mssql
    networks:
      - cocktail-net
    restart: always

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=sqlserverdata;User Id=sa;Password=YourStrong!Passw0rd;Encrypt=False;TrustServerCertificate=True
    volumes:
      - ./backend:/src
    working_dir: /src
    depends_on:
      - db
    networks:
      - cocktail-net
    restart: always

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: frontend
  #   ports:
  #     - "4200:80"
  #   volumes:
  #     - ./frontend:/app
  #   working_dir: /app
  #   command: npm run start -- --host 0.0.0.0
  #   depends_on:
  #     - backend
  #   networks:
  #     - cocktail-net
  #   restart: always

volumes:
  sqlserverdata:

networks:
  cocktail-net:
    driver: bridge
